name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app_id: 8ca56a92-9738-49cb-8b3c-570849860fad

      - name: Deployment
        uses: peter-evans/create-deployment@v3.1.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          environment: production
          production_environment: true
          auto_inactive: true
          required_contexts: '[]'
